---
title: Abby Brown
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: default
markdown: redcarpet
highlighter: pygments
permalink: "/:title"
locale: en_us
name: Abby Brown
tagline: a designer
description: description
url: designerd.ink
rss: rss feed url
baseurl: "/"
baseurl_posts_img: "/assets/images/posts/"
baseurl_featured_img: "/assets/images/hero/"
baseurl_featured_thumbnail: "/assets/images/thumbnail/"
baseurl_javascripts: "/assets/javascripts/"
icon: your site icon path
disqus: disqus_shortname
author:
  name: Abby Brown
  url: designerd.ink
  facebook: abby.brown.378
  twitter: abby_brown13
  handshake: users/6020175
fb_admins: your facebook profile id
fb_appid: your facebook app id
destination: "./_site"
exclude:
- ".editorconfig"
- ".gitignore"
- bower.json
- composer.json
- CONTRIBUTING.md
- CNAME
- LICENSE
- Gruntfile.js
- package.json
- node_modules
- README.md
- sass
- haml
port: 9001
